### ISSUE TITLE
[Question]  Create your server sent event outisde src/routes

### ISSUE THREAD

**Issue by elhananjair** [tncrazvan/sveltekit-sse#10]
Hello there, this is not a bug but rather a question, I have long running process inside `src/lib/server` folder. I want to create SSE inside that file to send some data to store `src/lib/store/mystore.js` and then I import this store in multiple svelte components to show the value. 

But reading sveltekit-sse documentation it seems I can only create SSE from routes, meanwhile, I am trying it with this:

 **/src/lib/server/longrunningtask.js**
```
/** src/lib/server/longrunningtask.js */

import { event } from 'sveltekit-sse'

export function GET() {
    return event(async emit => {
        while (true) {
            emit(`${Date.now()}`)
            await delay(1000)
        }
    }).toResponse()
}
```

**/src/lib/store/mystore.js**
```
/**  /src/lib/store/mystore.js  */

import { writable } from 'svelte/store';
import { source } from 'sveltekit-sse'

const value = source('http://localhost').onError(event => console.error({ event }))

const newVal = writable(value);
export default newVal;
```

**/src/lib/components/serverData.svelte**
```
/** /src/lib/components/serverData.svelte
      This component imported inside /src/routes/dashboard/+page.svelte
**/

import newVal from "../store/mystore.js"
console.log($newVal)

```
It outputs the following in terminal:

```
{
  close: [Function: close],
  subscribe: [Function: subscribe],
  onError: [Function: onError],
  setReconnect: [Function: setReconnect],
  setReconnectOnError: [Function: setReconnectOnError],
  select: [Function: select],
  transform: [Function (anonymous)]
}
```

**My questions are: **
1. I used HTTP:localhost source() as you can see, does this make any problem?
2. I am not getting the value I was expecting which is sent to the client each second, instead it is sending an object.

**Comment by tncrazvan** [comment]
I just released version 0.3.6 with some improvements to type hints, which will hopefully clarify these things more.

**Comment by elhananjair** [comment]
Hello @tncrazvan thanks for replying.

I have corrected my code as you showed above, but I am not getting anything from `console.log($value)` or inside `<p> {$value} </p>`
any thoughts on this?

I just want to store SSE data on the store so that different components can use it.

**Comment by tncrazvan** [comment]
Hey @elhananjair ,
as described in the code docs, the first value of the store is initialized to blank when using SSR (it wouldn't make sense for the server to connect to itself to fetch the data).
![image](https://github.com/tncrazvan/sveltekit-sse/assets/6891346/578935ae-fc19-45b8-bea5-143876ea5105)


My guess is that your `console.log` is not reactive thus only logging the first value, which would be blank.

I can't say for sure without reading the code.

Regardless, I just created this repository showcasing your use case: https://github.com/tncrazvan/sveltekit-sse-issue-10

All you need to do is clone it, install dependencies with `npm i` and invoke `npm run dev` in your terminal.

The result should look like this

![Peek 2023-10-17 13-20](https://github.com/tncrazvan/sveltekit-sse/assets/6891346/f7ebe506-ea73-4a2d-999f-68d25459d8c3)

**Comment by elhananjair** [comment]
Hello @tncrazvan thanks again for taking the time to reply.
I will check the repository you have created. 

I just copied this line:  `$: console.log($value)` and it still is not working. Here is how my code is structured:

```
src 
     |
       lib
           |
             components
                                   | 
                                     showssedata.svelte (is imported in +page.svelte
 
           |
             store
                      |
                        mystore.js  (is imported in showssedata.svelte)
     
            |
             server
                        | 
                          longrunningtask.js (imported inside hooks.server.js)
 
      |
        routes
                    |
                      Dashboard
                                          | 
                                            +page.svelte
 
      |
        hooks.server.js (executes longrunningtask.js)
```


I am guessing `hooks.server.js` is causing a problem since it executes only once. The long_running_task.js needs to be executed only once the server is up, that's why I put it inside `hooks.server.js`. 

I don't know if there is another way to do that so that I can get the result that I am expecting.

**Comment by elhananjair** [comment]
@tncrazvan I have updated my code with the way you have provided, and I am getting this error:

```
TypeError: Cannot read properties of undefined (reading 'status')
    at Module.respond (eval at instantiateModule PATH_TO_APP/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55917:28), <anonymous>:304:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PATH_TO_APP/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:510:22
Error: Invalid response from route /event: handler should return a Response object
    at Module.render_endpoint (eval at instantiateModule (PATH_TO_APP/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55917:28), <anonymous>:54:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (eval at instantiateModule (PATH_TO_APP/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55917:28), <anonymous>:412:17)
    at async Object.handle (eval at instantiateModule (PATH_TO_APP/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55917:28), <anonymous>:15:22)
    at async Module.respond (eval at instantiateModule (PATH_TO_APP/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55917:28), <anonymous>:282:20)
    at async PATH_TO_APP/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:510:22

```

**Comment by elhananjair** [comment]
![image](https://github.com/tncrazvan/sveltekit-sse/assets/69236638/dc996cc2-1a11-4e6a-8bc0-a96d2b65f140)


The error happens when I visit localhost:5173/dashboard

**Comment by elhananjair** [comment]
Your code is totally working I really can't tell what I am missing...

![image](https://github.com/tncrazvan/sveltekit-sse/assets/69236638/e96422ae-d214-4a2f-ab02-415359f49906)

--- 
![image](https://github.com/tncrazvan/sveltekit-sse/assets/69236638/34fb1229-2581-4f1f-974a-98b6e3355445)

**Comment by elhananjair** [comment]
Thank God finally, I could see the milliseconds starting to show up on the dashboard, I thought the console.log($event)... show up on my IDE instead of browser (my bad)

```

>   $: console.log($event)  
>   $: console.log($hooked_event)

```

About an issue I am seeing this in browser:

```
Uncaught (in promise) TypeError: state is undefined
    stop source.js:105
    subscribe2 index.js:88
    run utils.js:41
    run_all utils.js:53
    destroy_component Component.js:68
    destroy +page.svelte:456
    destroy_component Component.js:69
    update root.svelte:482
    transition_out transitions.js:89
    run utils.js:41
    run_all utils.js:53
    check_outros transitions.js:57
    update root.svelte:485
    update_slot_base utils.js:203
    update +layout.svelte:372
    update scheduler.js:119
    flush scheduler.js:79
    promise callback*schedule_update scheduler.js:20
    make_dirty Component.js:81
    ctx Component.js:129
    $$set root.svelte:948
    get proxy.js:83
    $set Component.js:489
    key proxy.js:46
    navigate client.js:1112
    _start_router client.js:1594
    _start_router client.js:1512
    start start.js:27
    async* whitelist:293
    promise callback* whitelist:292
```

**Comment by tncrazvan** [comment]
@elhananjair 
> About an issue I am seeing this in browser:

I think that's a bug I fixed recently.

Could you update to version `0.3.6` and let me know if the error goes away?

**Comment by elhananjair** [comment]
@tncrazvan Thank you so so much, and sorry for taking your time. 
It worked perfectly after I upgraded the package. 

Now I need to read how the code exactly working, I am a newcomer to Sveltekit and I didn't somehow understand the purpose of  `routes/event/+server.js`, `hooked_event.js`, and `event.js`

**Comment by elhananjair** [comment]
In my case I want to emit an event as some variable changes its value or on some another event I am listening inside some function call, I can still use return event... right?

**Comment by tncrazvan** [comment]
>  I didn't somehow understand the purpose of routes/event/+server.js, hooked_event.js, and event.js

- `event.js` is your old `mystore.js` file, I renamed it
- `hooked_event.js` is the same as `event.js`, but it points to a different url, it points to `/hooked_event` instead of `/event`
- `routes/event/+server.js` is just a svelte api route, it responds to the url `/event`.

  it's the equivalent of doing this in your `hooks.server.js`:
  ```js
  import { long_running_task } from '$lib/server/long_running_task'
  
  /** @type {import('@sveltejs/kit').Handle} */
  export async function handle({ event, resolve }) {
    if (event.url.pathname.startsWith('/event')) { // <=== Note this path
    return long_running_task()
    }
  
    const response = await resolve(event)
    return response
  }
  ```
You shouldn't really use `hook.server.js` to do this kind of thing, unless you want ALL your endpoints to reply with SSEs.\
If I were you I would just create 1 single file `src/routes/events/+server.js` and serve all my events from that endpoint.\
You can find an example how to do that [here](https://github.com/tncrazvan/sveltekit-sse#multiple-events).

**I will be closing this issue since it seems to be resolved.**

---

Other than that, I suggest you join the [Svelte Discord Server](https://discord.com/channels/457912077277855764/919220222379053086) or [r/sveltejs](https://www.reddit.com/r/sveltejs/) and ask any questions you have related to svelte in general there.

People over there are kind, helpful and pretty active.

**Comment by elhananjair** [comment]
Hello, @tncrazvan thank you so much for clarifying it for me.

> You shouldn't use hook.server.js to do this kind of thing, unless you want ALL your endpoints to reply with SSEs.
If I were you I would just create 1 single file src/routes/events/+server.js and serve all my events from that endpoint.
You can find an example how to do that [here](https://github.com/tncrazvan/sveltekit-sse#multiple-events).

Ok, I did like as you suggested, the reason I used `hook.server.js` is that I saw it executed as the application starts up so it is useful for something like initializing database and the like... 
The best thing I found in both is **(+server.js and hook.server.js)** is that they don't execute the exported function again and again. Which helps my long-running function to still run in the background without being affected by front-end actions. 

Currently, I am working on how to make the front end not be blocked while sending data from the server using SSE. Currently, with the large data I am working with it is blocking the front end, and the bad news is that Sveltekit has not implemented or supported nodejs `worker_thread`, I don't know if Web worker can fix this even though I think it only works for JS codes executed in the front end. 

Secondly, based on your suggestion (using +server.js), unless I reload the front end, I am not able to see the change in real-time. In the example you provided it emits the event with some delay, but in my case a variable I am sending gets changed within ms,  I don't if that is also a reason for that. 


>Other than that, I suggest you join the [Svelte Discord Server](https://discord.com/channels/457912077277855764/919220222379053086) or [r/sveltejs](https://www.reddit.com/r/sveltejs/) and ask any questions you have related to svelte in general there.

Yeah, I am in Svelte Discord Server which is an awesome place to learn from the community, but I haven't used Reddit before but I will check it out. 

Thanks.

**Comment by elhananjair** [comment]
Hello @tncrazvan 
I just decided that using `/event/+server.js` doesn't suit my needs. In my case it only executed when I clicked on a specific route where the component importing the store is found(like /dashboard/+page.svelte). 

But I wanted the `long_running_task` function to get executed as the application starts, so in that case `hooks.server.js` do the job the right way. I just mentioned this for your suggestion: 

> You shouldn't really use hook.server.js to do this kind of thing, unless you want ALL your endpoints to reply with SSEs.
If I were you I would just create 1 single file src/routes/events/+server.js and serve all my events from that endpoint.
You can find an example how to do that [here](https://github.com/tncrazvan/sveltekit-sse#multiple-events).

**Comment by elhananjair** [comment]
Hello @tncrazvan 
Just one question my front end doesn't update instantly, but only shows the data on reload?
Currently, I am implementing the SMPP protocol to send SMS, and I am updating a variable when there is a delivery receipt since I am working with an SMSC simulator the delivery receipt is received instantly, and I used the variable inside `emit`, the problem is my front- end hangs until the sending message function finishes the job, and I can only see the result of the variable on reload.
Is this caused because of the blocking running function?

**Comment by tncrazvan** [comment]
@elhananjair 
Nothing should be hanging as long as you're running non blocking code inside your event, but if you block the thread then obviously everything hangs, not just the sse stream.

It's got nothing to do with this library, it's how javascript works.

**Comment by tncrazvan** [comment]
@elhananjair please use the [Svelte Discord Server](https://discord.com/channels/457912077277855764/919220222379053086) or the [Svelte Reddit](https://www.reddit.com/r/sveltejs/) to ask questions unrelated to this library, otherwise other users who are looking for solutions will get confused when reading these issues in the future :smiley:

**Comment by elhananjair** [comment]
The function I am running in long_running_task.js is in sync mode, so it will block the UI for now I am thinking of using BullMQ for queuing. 
But what still confuses me about the library is that in the example you provided the function just emits an event in some interval, but in my case, I just want to send an event some specific variable gets updated inside the function. Something like this:

```
const smpp = require('smpp');
let sentSMS = 0;
export function long_running_task() {
var smpp = require('smpp');
var session = smpp.connect({
	url: 'smpp://example.com:2775',
	auto_enquire_link_period: 10000,
	debug: true
}, function() {
	session.bind_transceiver({
		system_id: 'YOUR_SYSTEM_ID',
		password: 'YOUR_PASSWORD'
	}, function(pdu) {
		if (pdu.command_status === 0) {
			// Successfully bound
			session.submit_sm({
				destination_addr: 'DESTINATION NUMBER',
				short_message: 'Hello!'
			}, function(pdu) {
				if (pdu.command_status === 0) {
					sentSMS++
					console.log(pdu.message_id);
				}
			});
		}
	});
});
  return event(async emit => {
      emit(`${sentSMS}`)
  }).toResponse()
}
```
This still shows the value but only on reload. 

**UPDATE:**
I am sorry I just saw your last message now, could you create a discussion on github maybe we can discuss it there.
