### ISSUE TITLE
Support SvelteKit v2

### ISSUE THREAD

**Issue by BearToCode** [tncrazvan/sveltekit-sse#18]
Hello, 
I've just updated to SvelteKit v2 and the library works fine. It would be nice to specify `"@sveltejs/kit": "^1.25. 2 || ^2.0.0"` in `package.json` to prevent a peer dependencies warning.
There is also this new warning when starting the dev server:
```
[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

sveltekit-sse@0.5.0

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

**Comment by tncrazvan** [comment]
[v0.5.2](https://github.com/tncrazvan/sveltekit-sse/releases/tag/0.5.2) is out and the warning is now gone.

Thank you for the issue!
